export default {
    MARK_NOTIFUCATION_AS_READ_BY_ID: 'MARK_NOTIFUCATION_AS_READ_BY_ID',
    MARK_ALLNOTIFUCATION_AS_READ: 'MARK_ALLNOTIFUCATION_AS_READ',
    START_MARK_AS_READ: 'START_MARK_AS_READ',
    FINISH_MARK_AS_READ: 'FINISH_MARK_AS_READ'
}